In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([1, 2, 3]).T

array([1, 2, 3])

In [4]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [5]:
np.array([1, 2, 3], ndmin=2).T

array([[1],
       [2],
       [3]])